export const  musicList = [
    '6IX9INE - GOOBA.mp3',
    'Ariana Grande - Social_House.mp3',
    'Arizona Zervas - ROXANNE.mp3',
    'Arizona Zervas - ZIUS.mp3',
    'B.o.B - Airplanes.mp3',
    'Bon Jovi - Its My Life.mp3',
    'Can Kan - Yaranamadım.mp3',
    'Charlie Puth - Mother_Official.mp3',
    'Clean Bandit - Rockabye.mp3',
    'Demi - Lovato_I_Love_Me.mp3',
    'Doja - Cat Say So.mp3',
    'Dua Lipa - Break My Heart.mp3',
    "Dua Lipa - Don't Start Now.mp3",
    'Dua Lipa - Physical.mp3',
    'Ed Sheeran - Beautiful People.mp3',
    'Ed Sheeran - Galway Girl.mp3',
    'Ed Sheeran - Shape of You.mp3',
    'Evanescence - Bring Me To Life.mp3',
    'Grup Vitamin - Al Aşkını.mp3',
    'Grup Vitamin - Törkiş Kovboylar.mp3',
    'Hoobastank - The Reason.mp3',
    'Justin Bieber - Forever.mp3',
    'JustinBieber - Intentions ft Qua.mp3',
    'Kiss - I Was Made For Lovin.mp3',
    'Lil Mosey - Blueberry Faygo.mp3',
    'Maroon 5 - Memories.mp3',
    'Mendes - Camila_Cabello.mp3',
    'Michael Jackson - They Dont Care.mp3',
    'Mr. Big - Wild World.mp3',
    'Necati ve Saykolar - Fırtına.mp3',
    'Oğuzhan Uğur - Madım mı.mp3',
    'PARTYNEXTDOOR - BELIEVE IT.mp3',
    'Queen - Bohemian Rhapsody.mp3',
    'Roddy Ricch - The Box.mp3',
    'Sam Smith - How Do You.mp3',
    'Selena Gomez -Lose_You.mp3',
/*     'The Weeknd - Blinding_Lights.mp3',
    'The Weeknd - Heartless.mp3',
    'Tiësto - God Is A Dancer.mp3',
    'TONES- DANCE MONKEY.mp3',
    'Trevor Daniel - Falling.mp3',
    'Yaşandı Bitti  - Burak Kut.mp3',
    'Zedd & Kehlani - Good Thing.mp3' */
  ]


